# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0004_auto_20170724_0943'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
        migrations.AddField(
            model_name='token',
            name='last_request_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
