# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0005_auto_20170724_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='last_request_on',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
