# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0008_auto_20170725_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(upload_to=b'\\user_images'),
        ),
    ]
