# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0015_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='tag',
            field=models.CharField(max_length=2000),
        ),
    ]
